services:
  api: 
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"
    environment:
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_SCHEMA=${DB_SCHEMA}
      - PORT=${PORT}
    networks:
      - foo

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - db:/var/lib/postgresql/data
    networks:
        - foo

volumes:
  db:

networks:
  foo:
